// Builds public/runners/daily.js = src/core/rates-core.js (without `export`) + src/runner/daily.js
// The background runner is a plain script (no modules), so the shared code is pasted in front.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const core = readFileSync(resolve(root, 'src/core/rates-core.js'), 'utf8');
const runner = readFileSync(resolve(root, 'src/runner/daily.js'), 'utf8');

if (/^\s*import\s/m.test(core)) throw new Error('rates-core.js must not use import');
const plainCore = core.replace(/^export\s+(?=(async\s+)?function|const)/gm, '');
if (/^export\s/m.test(plainCore)) throw new Error('rates-core.js has an export the runner build cannot strip');

const out = resolve(root, 'public/runners/daily.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  '// GENERATED by scripts/build-runner.mjs — do not edit. Sources: src/core/rates-core.js, src/runner/daily.js\n' +
    plainCore + '\n' + runner,
);
console.log('runner written:', out);
